<?php

use Illuminate\Database\Seeder;

use App\Attributes;

class AttributeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //

        $arr = [
            [
                'code' => 'sku',
                'admin_name' => 'Sku',
                'type' => 'text',
                'validation' => 'string|max:255',
                'position' => 0,
                'is_required' => 1,
                'is_unique' => 1,
                'is_filterable' => 0,
                'is_configurable' => 0,
                'is_visible_on_front' => 1,
                'is_user_defined' => 0,
            ],
            [
                'code' => 'name',
                'admin_name' => 'Name',
                'type' => 'text',
                'validation' => 'string|max:255',
                'position' => 0,
                'is_required' => 1,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_configurable' => 0,
                'is_visible_on_front' => 1,
                'is_user_defined' => 0,
            ],
            [
                'code' => 'price',
                'admin_name' => 'Price',
                'type' => 'text',
                'validation' => 'string|numeric',
                'position' => 0,
                'is_required' => 1,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_configurable' => 0,
                'is_visible_on_front' => 1,
                'is_user_defined' => 0,
            ],
            [
                'code' => 'url_key',
                'admin_name' => 'Url key',
                'type' => 'text',
                'validation' => 'string|max:254',
                'position' => 0,
                'is_required' => 1,
                'is_unique' => 1,
                'is_filterable' => 0,
                'is_configurable' => 0,
                'is_visible_on_front' => 1,
                'is_user_defined' => 0,
            ],
            [
                'code' => 'is_new',
                'admin_name' => 'Is New',
                'type' => 'boolean',
                'validation' => '',
                'position' => 0,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_configurable' => 0,
                'is_visible_on_front' => 1,
                'is_user_defined' => 0,
            ],
            [
                'code' => 'is_featured',
                'admin_name' => 'Is Featured',
                'type' => 'boolean',
                'validation' => '',
                'position' => 0,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_configurable' => 0,
                'is_visible_on_front' => 1,
                'is_user_defined' => 0,
            ],
            [
                'code' => 'visible',
                'admin_name' => 'Visible',
                'type' => 'boolean',
                'validation' => 'required',
                'position' => 0,
                'is_required' => 1,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_configurable' => 0,
                'is_visible_on_front' => 1,
                'is_user_defined' => 0,
            ],
            [
                'code' => 'status',
                'admin_name' => 'Status',
                'type' => 'boolean',
                'validation' => 'required',
                'position' => 0,
                'is_required' => 1,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_configurable' => 0,
                'is_visible_on_front' => 1,
                'is_user_defined' => 0,
            ],
            [
                'code' => 'sort_description',
                'admin_name' => 'Sort description',
                'type' => 'textarea',
                'validation' => '',
                'position' => 0,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_configurable' => 0,
                'is_visible_on_front' => 1,
                'is_user_defined' => 0,
            ],
            [
                'code' => 'description',
                'admin_name' => 'Description',
                'type' => 'textarea',
                'validation' => '',
                'position' => 0,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_configurable' => 0,
                'is_visible_on_front' => 1,
                'is_user_defined' => 0,
            ],
            [
                'code' => 'special_price',
                'admin_name' => 'Special price',
                'type' => 'text',
                'validation' => 'decimal',
                'position' => 0,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_configurable' => 0,
                'is_visible_on_front' => 1,
                'is_user_defined' => 0,
            ],
            [
                'code' => 'special_price_from',
                'admin_name' => 'Special price from',
                'type' => 'date',
                'validation' => '',
                'position' => 0,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_configurable' => 0,
                'is_visible_on_front' => 1,
                'is_user_defined' => 0,
            ],
            [
                'code' => 'special_price_to',
                'admin_name' => 'Special price to',
                'type' => 'date',
                'validation' => '',
                'position' => 0,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_configurable' => 0,
                'is_visible_on_front' => 1,
                'is_user_defined' => 0,
            ],
            [
                'code' => 'width',
                'admin_name' => 'Width',
                'type' => 'text',
                'validation' => 'decimal',
                'position' => 0,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_configurable' => 0,
                'is_visible_on_front' => 1,
                'is_user_defined' => 0,
            ],
            [
                'code' => 'height',
                'admin_name' => 'Height',
                'type' => 'text',
                'validation' => 'decimal',
                'position' => 0,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_configurable' => 0,
                'is_visible_on_front' => 1,
                'is_user_defined' => 0,
            ],
            [
                'code' => 'depth',
                'admin_name' => 'Depth',
                'type' => 'text',
                'validation' => 'decimal',
                'position' => 0,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_configurable' => 0,
                'is_visible_on_front' => 1,
                'is_user_defined' => 0,
            ],
            [
                'code' => 'weight',
                'admin_name' => 'Weight',
                'type' => 'text',
                'validation' => 'decimal',
                'position' => 0,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_configurable' => 0,
                'is_visible_on_front' => 1,
                'is_user_defined' => 0,
            ],
            [
                'code' => 'size',
                'admin_name' => 'Size',
                'type' => 'select',
                'validation' => '',
                'position' => 0,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 1,
                'is_configurable' => 1,
                'is_visible_on_front' => 1,
                'is_user_defined' => 0,
            ],
            [
                'code' => 'color',
                'admin_name' => 'Color',
                'type' => 'select',
                'validation' => '',
                'position' => 0,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 1,
                'is_configurable' => 1,
                'is_visible_on_front' => 1,
                'is_user_defined' => 0,
            ]
        ];

        foreach ( $arr as $item ){
            Attributes::create($item);
        }
    }
}
